#version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - /databases/mongo/data:/data/db
      - /databases/mongo/mongod.conf:/etc/mongod.conf
#    command: mongod --config /etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=AdHocTuts2019@
    ports:
      - "27017:27017"